### ISSUE TITLE
Module: Interface between Memory components and AHB subordinate module

### ISSUE THREAD

**Issue by SPD3** [NYU-Processor-Design/nyu-mem#1]
The Memory Controller must be able to communicate with the Advanced High-Performance Bus through a subordinate so that all parts of the processor that need to can access memory. The interface between these two integral components needs to be:
1. Planned out.
2. Stubbed out in code
3. Implemented in code

**Comment by rishyak** [comment]
Memory Controller Control Signals:

**Inputs**
1. Address
2. Read/Write bit
3. Data (`wdata[31:0]`)

**Output**
1. Data (`rdata[31:0]`)

**Comment by rishyak** [comment]
Interface is ready, subordinate needs implementation.
